version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n-teraanalyser
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=0.0.0.0  # <-- ESSA LINHA É ESSENCIAL
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - TZ=America/Sao_Paulo
    volumes:
      - C:/Users/Thiago Alcantara/.n8n:/home/node/.n8n
